version: "3"
services:
  webapi:
    build: .
    restart: on-failure
    stdin_open: true
    tty: true
    env_file:
      - ./.env
      - ./.env.secret
    # command: gunicorn gee_bridge.wsgi:application --config ./gunicorn.conf.py
    # command: pipenv run supervisord -c supervisord.conf
    # command: gunicorn -b 0.0.0.0:8081 --env DJANGO_SETTINGS_MODULE=gee_bridge.settings gee_bridge.wsgi --timeout 120 --workers=3 --log-file /tmp/gee_bridge.log --log-level debug
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    image: "postgres:10.3-alpine"
    restart: always
    env_file:
        - ./.env.secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
